-- Pruebas rápidas para confirmar que el dataset está disponible.

SELECT COUNT(*) AS CLIENTES FROM CLIENTES;
SELECT COUNT(*) AS PRODUCTOS FROM PRODUCTOS;
SELECT COUNT(*) AS VENTAS FROM VENTAS;
SELECT COUNT(*) AS DETALLES FROM DETALLE_VENTA;
SELECT COUNT(*) AS CLIENTE_PRODUCTO FROM CLIENTE_PRODUCTO;
SELECT COUNT(*) AS RECOMENDACIONES FROM RECOMENDACIONES;

SELECT *
FROM (
    SELECT V.VENTA_ID, V.FOLIO, V.FECHA_VENTA, C.NOMBRE AS CLIENTE, V.TOTAL
    FROM VENTAS V
    JOIN CLIENTES C ON C.CLIENTE_ID = V.CLIENTE_ID
    ORDER BY V.FECHA_VENTA DESC
)
WHERE ROWNUM <= 10;
