-- ARTEFACTA Copiloto - validaciones para Entrega 2

SELECT COUNT(*) AS CLIENTE_PRODUCTO_TOTAL
FROM CLIENTE_PRODUCTO;

SELECT COUNT(*) AS CLIENTE_PRODUCTO_CON_PATRON
FROM CLIENTE_PRODUCTO
WHERE NUM_COMPRAS >= 2
  AND ULTIMA_COMPRA IS NOT NULL
  AND PROMEDIO_DIAS_COMPRA IS NOT NULL;

SELECT ESTATUS, COUNT(*) AS CANTIDAD
FROM RECOMENDACIONES
GROUP BY ESTATUS
ORDER BY ESTATUS;

SELECT TIPO, PRIORIDAD, COUNT(*) AS CANTIDAD
FROM RECOMENDACIONES
GROUP BY TIPO, PRIORIDAD
ORDER BY TIPO, PRIORIDAD;

SELECT COUNT(*) AS HISTORIAL
FROM HISTORIAL_RECOMENDACION;
