-- ============================================================
-- SISTEMA DE VENTAS - MODELO INICIAL PARA ORACLE 19c
-- ============================================================
-- Nota:
-- 1) Ejecutar con un usuario con permisos para crear tablas, índices
--    y secuencias dentro del esquema de la aplicación.
-- 2) No incluye contraseñas reales.
-- 3) Las tablas CLIENTE_PRODUCTO y RECOMENDACIONES son analíticas.
-- ============================================================

-- =========================
-- SECUENCIAS
-- =========================
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORIAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VENDEDORES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ROLES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VENTAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETALLE_VENTA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROMOCIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECOMENDACIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HIST_RECOMENDACION START WITH 1 INCREMENT BY 1 NOCACHE;

-- =========================
-- CLIENTES
-- =========================
CREATE TABLE CLIENTES (
    CLIENTE_ID       NUMBER(12)       NOT NULL,
    CODIGO_CLIENTE   VARCHAR2(30)     NOT NULL,
    NOMBRE           VARCHAR2(150)    NOT NULL,
    RAZON_SOCIAL     VARCHAR2(200),
    RFC              VARCHAR2(13),
    EMAIL            VARCHAR2(150),
    TELEFONO         VARCHAR2(30),
    FECHA_ALTA       DATE DEFAULT SYSDATE NOT NULL,
    ACTIVO           NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT UK_CLIENTES_CODIGO UNIQUE (CODIGO_CLIENTE),
    CONSTRAINT UK_CLIENTES_RFC UNIQUE (RFC),
    CONSTRAINT CK_CLIENTES_ACTIVO CHECK (ACTIVO IN (0,1))
);

-- =========================
-- CATEGORIAS
-- =========================
CREATE TABLE CATEGORIAS (
    CATEGORIA_ID NUMBER(12) NOT NULL,
    NOMBRE       VARCHAR2(100) NOT NULL,
    DESCRIPCION  VARCHAR2(500),
    ACTIVO       NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY (CATEGORIA_ID),
    CONSTRAINT UK_CATEGORIAS_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_CATEGORIAS_ACTIVO CHECK (ACTIVO IN (0,1))
);

-- =========================
-- PRODUCTOS
-- =========================
CREATE TABLE PRODUCTOS (
    PRODUCTO_ID      NUMBER(12) NOT NULL,
    CODIGO_PRODUCTO  VARCHAR2(50) NOT NULL,
    SKU              VARCHAR2(80),
    NOMBRE           VARCHAR2(200) NOT NULL,
    DESCRIPCION      VARCHAR2(1000),
    CATEGORIA_ID     NUMBER(12),
    PRECIO           NUMBER(15,2) DEFAULT 0 NOT NULL,
    COSTO            NUMBER(15,2),
    ACTIVO           NUMBER(1) DEFAULT 1 NOT NULL,
    FECHA_ALTA       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (PRODUCTO_ID),
    CONSTRAINT UK_PRODUCTOS_CODIGO UNIQUE (CODIGO_PRODUCTO),
    CONSTRAINT UK_PRODUCTOS_SKU UNIQUE (SKU),
    CONSTRAINT FK_PRODUCTOS_CATEGORIA
        FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(CATEGORIA_ID),
    CONSTRAINT CK_PRODUCTOS_PRECIO CHECK (PRECIO >= 0),
    CONSTRAINT CK_PRODUCTOS_COSTO CHECK (COSTO IS NULL OR COSTO >= 0),
    CONSTRAINT CK_PRODUCTOS_ACTIVO CHECK (ACTIVO IN (0,1))
);

-- =========================
-- VENDEDORES
-- =========================
CREATE TABLE VENDEDORES (
    VENDEDOR_ID      NUMBER(12) NOT NULL,
    CODIGO_VENDEDOR  VARCHAR2(30) NOT NULL,
    NOMBRE           VARCHAR2(150) NOT NULL,
    EMAIL            VARCHAR2(150),
    TELEFONO         VARCHAR2(30),
    FECHA_ALTA       DATE DEFAULT SYSDATE NOT NULL,
    ACTIVO           NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_VENDEDORES PRIMARY KEY (VENDEDOR_ID),
    CONSTRAINT UK_VENDEDORES_CODIGO UNIQUE (CODIGO_VENDEDOR),
    CONSTRAINT CK_VENDEDORES_ACTIVO CHECK (ACTIVO IN (0,1))
);

-- =========================
-- ROLES
-- =========================
CREATE TABLE ROLES (
    ROL_ID       NUMBER(12) NOT NULL,
    NOMBRE       VARCHAR2(50) NOT NULL,
    DESCRIPCION  VARCHAR2(250),
    CONSTRAINT PK_ROLES PRIMARY KEY (ROL_ID),
    CONSTRAINT UK_ROLES_NOMBRE UNIQUE (NOMBRE)
);

-- =========================
-- USUARIOS
-- =========================
CREATE TABLE USUARIOS (
    USUARIO_ID       NUMBER(12) NOT NULL,
    USERNAME         VARCHAR2(100) NOT NULL,
    PASSWORD_HASH    VARCHAR2(255) NOT NULL,
    NOMBRE           VARCHAR2(150) NOT NULL,
    EMAIL            VARCHAR2(150),
    VENDEDOR_ID      NUMBER(12),
    ACTIVO           NUMBER(1) DEFAULT 1 NOT NULL,
    FECHA_ALTA       DATE DEFAULT SYSDATE NOT NULL,
    ULTIMO_ACCESO    TIMESTAMP,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIO_ID),
    CONSTRAINT UK_USUARIOS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT FK_USUARIOS_VENDEDOR
        FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDORES(VENDEDOR_ID),
    CONSTRAINT CK_USUARIOS_ACTIVO CHECK (ACTIVO IN (0,1))
);

-- =========================
-- USUARIO_ROL
-- =========================
CREATE TABLE USUARIO_ROL (
    USUARIO_ID NUMBER(12) NOT NULL,
    ROL_ID     NUMBER(12) NOT NULL,
    CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (USUARIO_ID, ROL_ID),
    CONSTRAINT FK_USUARIO_ROL_USUARIO
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID),
    CONSTRAINT FK_USUARIO_ROL_ROL
        FOREIGN KEY (ROL_ID) REFERENCES ROLES(ROL_ID)
);

-- =========================
-- VENTAS
-- =========================
CREATE TABLE VENTAS (
    VENTA_ID       NUMBER(12) NOT NULL,
    FOLIO          VARCHAR2(40) NOT NULL,
    CLIENTE_ID     NUMBER(12) NOT NULL,
    VENDEDOR_ID    NUMBER(12),
    FECHA_VENTA    DATE DEFAULT SYSDATE NOT NULL,
    SUBTOTAL       NUMBER(15,2) DEFAULT 0 NOT NULL,
    DESCUENTO      NUMBER(15,2) DEFAULT 0 NOT NULL,
    IMPUESTO       NUMBER(15,2) DEFAULT 0 NOT NULL,
    TOTAL          NUMBER(15,2) DEFAULT 0 NOT NULL,
    ESTATUS        VARCHAR2(20) DEFAULT 'COMPLETADA' NOT NULL,
    CONSTRAINT PK_VENTAS PRIMARY KEY (VENTA_ID),
    CONSTRAINT UK_VENTAS_FOLIO UNIQUE (FOLIO),
    CONSTRAINT FK_VENTAS_CLIENTE
        FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID),
    CONSTRAINT FK_VENTAS_VENDEDOR
        FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDORES(VENDEDOR_ID),
    CONSTRAINT CK_VENTAS_SUBTOTAL CHECK (SUBTOTAL >= 0),
    CONSTRAINT CK_VENTAS_DESCUENTO CHECK (DESCUENTO >= 0),
    CONSTRAINT CK_VENTAS_IMPUESTO CHECK (IMPUESTO >= 0),
    CONSTRAINT CK_VENTAS_TOTAL CHECK (TOTAL >= 0),
    CONSTRAINT CK_VENTAS_ESTATUS
        CHECK (ESTATUS IN ('BORRADOR','COMPLETADA','CANCELADA'))
);

-- =========================
-- DETALLE DE VENTA
-- =========================
CREATE TABLE DETALLE_VENTA (
    DETALLE_VENTA_ID NUMBER(12) NOT NULL,
    VENTA_ID         NUMBER(12) NOT NULL,
    PRODUCTO_ID      NUMBER(12) NOT NULL,
    CANTIDAD         NUMBER(15,4) NOT NULL,
    PRECIO_UNITARIO  NUMBER(15,2) NOT NULL,
    DESCUENTO        NUMBER(15,2) DEFAULT 0 NOT NULL,
    IMPORTE          NUMBER(15,2) NOT NULL,
    CONSTRAINT PK_DETALLE_VENTA PRIMARY KEY (DETALLE_VENTA_ID),
    CONSTRAINT FK_DETALLE_VENTA_VENTA
        FOREIGN KEY (VENTA_ID) REFERENCES VENTAS(VENTA_ID),
    CONSTRAINT FK_DETALLE_VENTA_PRODUCTO
        FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(PRODUCTO_ID),
    CONSTRAINT CK_DETALLE_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_DETALLE_PRECIO CHECK (PRECIO_UNITARIO >= 0),
    CONSTRAINT CK_DETALLE_DESCUENTO CHECK (DESCUENTO >= 0),
    CONSTRAINT CK_DETALLE_IMPORTE CHECK (IMPORTE >= 0)
);

-- =========================
-- PROMOCIONES
-- =========================
CREATE TABLE PROMOCIONES (
    PROMOCION_ID     NUMBER(12) NOT NULL,
    NOMBRE           VARCHAR2(150) NOT NULL,
    DESCRIPCION      VARCHAR2(1000),
    TIPO             VARCHAR2(30) NOT NULL,
    VALOR            NUMBER(15,2) NOT NULL,
    FECHA_INICIO     DATE NOT NULL,
    FECHA_FIN        DATE NOT NULL,
    MINIMO_COMPRA    NUMBER(15,2) DEFAULT 0 NOT NULL,
    ACTIVO           NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_PROMOCIONES PRIMARY KEY (PROMOCION_ID),
    CONSTRAINT CK_PROMO_TIPO
        CHECK (TIPO IN ('DESCUENTO','MONTO_FIJO','PRECIO_ESPECIAL','BONIFICACION')),
    CONSTRAINT CK_PROMO_VALOR CHECK (VALOR >= 0),
    CONSTRAINT CK_PROMO_MINIMO CHECK (MINIMO_COMPRA >= 0),
    CONSTRAINT CK_PROMO_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT CK_PROMO_ACTIVO CHECK (ACTIVO IN (0,1))
);

-- =========================
-- PROMOCION_PRODUCTO
-- =========================
CREATE TABLE PROMOCION_PRODUCTO (
    PROMOCION_ID NUMBER(12) NOT NULL,
    PRODUCTO_ID  NUMBER(12) NOT NULL,
    CONSTRAINT PK_PROMOCION_PRODUCTO PRIMARY KEY (PROMOCION_ID, PRODUCTO_ID),
    CONSTRAINT FK_PP_PROMOCION
        FOREIGN KEY (PROMOCION_ID) REFERENCES PROMOCIONES(PROMOCION_ID),
    CONSTRAINT FK_PP_PRODUCTO
        FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(PRODUCTO_ID)
);

-- =========================
-- PROMOCION_CLIENTE
-- =========================
CREATE TABLE PROMOCION_CLIENTE (
    PROMOCION_ID       NUMBER(12) NOT NULL,
    CLIENTE_ID         NUMBER(12) NOT NULL,
    FECHA_ASIGNACION   DATE DEFAULT SYSDATE NOT NULL,
    FECHA_EXPIRACION   DATE,
    ESTATUS             VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    CONSTRAINT PK_PROMOCION_CLIENTE PRIMARY KEY (PROMOCION_ID, CLIENTE_ID),
    CONSTRAINT FK_PC_PROMOCION
        FOREIGN KEY (PROMOCION_ID) REFERENCES PROMOCIONES(PROMOCION_ID),
    CONSTRAINT FK_PC_CLIENTE
        FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID),
    CONSTRAINT CK_PC_ESTATUS
        CHECK (ESTATUS IN ('PENDIENTE','VISTA','ACEPTADA','RECHAZADA','EXPIRADA'))
);

-- =========================
-- CLIENTE_PRODUCTO
-- Resumen analítico generado a partir de ventas.
-- =========================
CREATE TABLE CLIENTE_PRODUCTO (
    CLIENTE_ID            NUMBER(12) NOT NULL,
    PRODUCTO_ID           NUMBER(12) NOT NULL,
    PRIMERA_COMPRA       DATE,
    ULTIMA_COMPRA        DATE,
    NUM_COMPRAS          NUMBER(12) DEFAULT 0 NOT NULL,
    CANTIDAD_TOTAL       NUMBER(18,4) DEFAULT 0 NOT NULL,
    IMPORTE_TOTAL        NUMBER(18,2) DEFAULT 0 NOT NULL,
    PROMEDIO_DIAS_COMPRA NUMBER(12,2),
    TICKET_PROMEDIO      NUMBER(18,2),
    FECHA_ACTUALIZACION  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CLIENTE_PRODUCTO PRIMARY KEY (CLIENTE_ID, PRODUCTO_ID),
    CONSTRAINT FK_CP_CLIENTE
        FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID),
    CONSTRAINT FK_CP_PRODUCTO
        FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(PRODUCTO_ID),
    CONSTRAINT CK_CP_NUM_COMPRAS CHECK (NUM_COMPRAS >= 0),
    CONSTRAINT CK_CP_CANTIDAD CHECK (CANTIDAD_TOTAL >= 0),
    CONSTRAINT CK_CP_IMPORTE CHECK (IMPORTE_TOTAL >= 0)
);

-- =========================
-- RECOMENDACIONES
-- =========================
CREATE TABLE RECOMENDACIONES (
    RECOMENDACION_ID  NUMBER(12) NOT NULL,
    CLIENTE_ID        NUMBER(12) NOT NULL,
    PRODUCTO_ID       NUMBER(12),
    TIPO              VARCHAR2(40) NOT NULL,
    SCORE             NUMBER(6,2) NOT NULL,
    PRIORIDAD         VARCHAR2(20) NOT NULL,
    MOTIVO            VARCHAR2(1000) NOT NULL,
    FECHA_GENERACION  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_EXPIRACION  TIMESTAMP,
    ESTATUS           VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    CONSTRAINT PK_RECOMENDACIONES PRIMARY KEY (RECOMENDACION_ID),
    CONSTRAINT FK_REC_CLIENTE
        FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID),
    CONSTRAINT FK_REC_PRODUCTO
        FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(PRODUCTO_ID),
    CONSTRAINT CK_REC_SCORE CHECK (SCORE BETWEEN 0 AND 100),
    CONSTRAINT CK_REC_PRIORIDAD
        CHECK (PRIORIDAD IN ('BAJA','MEDIA','ALTA','CRITICA')),
    CONSTRAINT CK_REC_ESTATUS
        CHECK (ESTATUS IN ('PENDIENTE','CONTACTADO','ACEPTADA','RECHAZADA','EXPIRADA'))
);

-- =========================
-- HISTORIAL DE RECOMENDACIONES
-- =========================
CREATE TABLE HISTORIAL_RECOMENDACION (
    HISTORIAL_ID      NUMBER(12) NOT NULL,
    RECOMENDACION_ID  NUMBER(12) NOT NULL,
    FECHA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACCION            VARCHAR2(40) NOT NULL,
    USUARIO_ID        NUMBER(12),
    RESULTADO         VARCHAR2(1000),
    CONSTRAINT PK_HIST_RECOMENDACION PRIMARY KEY (HISTORIAL_ID),
    CONSTRAINT FK_HIST_RECOMENDACION
        FOREIGN KEY (RECOMENDACION_ID) REFERENCES RECOMENDACIONES(RECOMENDACION_ID),
    CONSTRAINT FK_HIST_USUARIO
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID)
);

-- =========================
-- INDICES
-- =========================
CREATE INDEX IX_CLIENTES_NOMBRE
    ON CLIENTES(NOMBRE);

CREATE INDEX IX_CLIENTES_ACTIVO
    ON CLIENTES(ACTIVO);

CREATE INDEX IX_PRODUCTOS_CATEGORIA
    ON PRODUCTOS(CATEGORIA_ID);

CREATE INDEX IX_PRODUCTOS_NOMBRE
    ON PRODUCTOS(NOMBRE);

CREATE INDEX IX_VENTAS_CLIENTE_FECHA
    ON VENTAS(CLIENTE_ID, FECHA_VENTA);

CREATE INDEX IX_VENTAS_VENDEDOR_FECHA
    ON VENTAS(VENDEDOR_ID, FECHA_VENTA);

CREATE INDEX IX_VENTAS_FECHA
    ON VENTAS(FECHA_VENTA);

CREATE INDEX IX_VENTAS_ESTATUS_FECHA
    ON VENTAS(ESTATUS, FECHA_VENTA);

CREATE INDEX IX_DETALLE_PRODUCTO
    ON DETALLE_VENTA(PRODUCTO_ID);

CREATE INDEX IX_DETALLE_VENTA
    ON DETALLE_VENTA(VENTA_ID);

CREATE INDEX IX_PC_CLIENTE
    ON PROMOCION_CLIENTE(CLIENTE_ID);

CREATE INDEX IX_PP_PRODUCTO
    ON PROMOCION_PRODUCTO(PRODUCTO_ID);

CREATE INDEX IX_REC_CLIENTE_FECHA
    ON RECOMENDACIONES(CLIENTE_ID, FECHA_GENERACION);

CREATE INDEX IX_REC_PRIORIDAD
    ON RECOMENDACIONES(PRIORIDAD, ESTATUS);

CREATE INDEX IX_CP_PRODUCTO
    ON CLIENTE_PRODUCTO(PRODUCTO_ID);

-- =========================
-- DATOS INICIALES: ROLES
-- =========================
INSERT INTO ROLES (ROL_ID, NOMBRE, DESCRIPCION)
VALUES (SEQ_ROLES.NEXTVAL, 'ADMIN', 'Administrador del sistema');

INSERT INTO ROLES (ROL_ID, NOMBRE, DESCRIPCION)
VALUES (SEQ_ROLES.NEXTVAL, 'GERENTE', 'Gerente comercial');

INSERT INTO ROLES (ROL_ID, NOMBRE, DESCRIPCION)
VALUES (SEQ_ROLES.NEXTVAL, 'SUPERVISOR', 'Supervisor de ventas');

INSERT INTO ROLES (ROL_ID, NOMBRE, DESCRIPCION)
VALUES (SEQ_ROLES.NEXTVAL, 'VENDEDOR', 'Usuario vendedor');

INSERT INTO ROLES (ROL_ID, NOMBRE, DESCRIPCION)
VALUES (SEQ_ROLES.NEXTVAL, 'CONSULTA', 'Usuario de solo consulta');

COMMIT;

-- ============================================================
-- CONSULTA DE VALIDACION
-- ============================================================
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'CLIENTES',
    'CATEGORIAS',
    'PRODUCTOS',
    'VENDEDORES',
    'USUARIOS',
    'ROLES',
    'USUARIO_ROL',
    'VENTAS',
    'DETALLE_VENTA',
    'PROMOCIONES',
    'PROMOCION_PRODUCTO',
    'PROMOCION_CLIENTE',
    'CLIENTE_PRODUCTO',
    'RECOMENDACIONES',
    'HISTORIAL_RECOMENDACION'
)
ORDER BY TABLE_NAME;
